const animationLink = document.createElement('link');
animationLink.rel = 'stylesheet';
animationLink.href = 'assets/animations.css?motion=5';
document.head.appendChild(animationLink);

let currentPage = window.location.pathname.split('/').pop() || 'index.html';
let softNavigating = false;

const toggle = document.querySelector('.menu-toggle');
const nav = document.querySelector('.nav');
const topButton = document.querySelector('.back-to-top');
const transitionCover = document.createElement('div');
transitionCover.className = 'page-transition-cover';
document.body.appendChild(transitionCover);

const style = document.createElement('style');
style.textContent = `
  .crest{width:168px!important;height:52px!important;border:0!important;border-radius:0!important;background:transparent url('assets/sfu-logo.svg?logo=8') center/contain no-repeat!important;color:transparent!important;font-size:0!important;flex:0 0 168px!important}
  .brand{gap:1rem!important}.brand>span:last-child strong{color:#7a1f2d!important}
  .language-switcher{display:inline-flex;gap:.32rem;align-items:center}.utility-bar .language-switcher{margin-left:.8rem;padding-left:.8rem;border-left:1px solid rgba(255,255,255,.25)}
  .language-switcher button{border:1px solid rgba(255,255,255,.4);background:transparent;color:#fff;border-radius:999px;padding:.25rem .68rem;font-size:.78rem;font-weight:900;cursor:pointer;white-space:nowrap;transition:.2s ease}
  .language-switcher button.active,.language-switcher button:hover{background:#fff;color:#7a1f2d}.mobile-language-switcher,.mobile-utility-links{display:none}
  .mobile-utility-links{padding:.75rem;border-bottom:1px solid #e4d7cd;background:#fffaf3;gap:.45rem;grid-template-columns:repeat(2,minmax(0,1fr))}.mobile-utility-links a{display:block;padding:.65rem .75rem!important;border:1px solid #e4d7cd!important;border-radius:10px!important;background:#fff!important;color:#7a1f2d!important;font-size:.86rem!important;text-align:center}
  main{transition:opacity .18s ease,transform .18s ease}.main-leave{opacity:.25;transform:translateY(8px)}.main-enter{animation:mainEnter .26s ease both}@keyframes mainEnter{from{opacity:.25;transform:translateY(8px)}to{opacity:1;transform:translateY(0)}}
  @media(max-width:760px){.main-header{gap:.55rem!important;flex-wrap:wrap!important}.crest{width:132px!important;height:38px!important;flex-basis:132px!important}.brand>span:last-child{display:none!important}.mobile-language-switcher{display:inline-flex;width:100%;order:3;justify-content:flex-end;margin-top:.2rem}.main-header .language-switcher button{border-color:#e4d7cd;color:#7a1f2d;background:#fffaf3;padding:.34rem .62rem;font-size:.78rem}.main-header .language-switcher button.active,.main-header .language-switcher button:hover{background:#7a1f2d;color:#fff;border-color:#7a1f2d}.nav.open .mobile-utility-links{display:grid}}
`;
document.head.appendChild(style);

const ZH = {
  common:{university:'聖方濟各大學',site:'人工智能及資訊通訊科技課程資訊',util:['最新消息','立即申請','學生支援','搜尋'],nav:['入學資訊','課程列表','高級文憑','人工智能學士','升學銜接','獎學金','畢業出路','業界合作'],lang:['繁體中文','English','简体中文'],footer:'資料以 SFUHK 及 JUPAS 最新官方公布為準。',mobile:['最新消息','立即申請','學生支援','搜尋 / 常見問題']},
  pages:{
    'index.html':{title:'SFUHK 人工智能及資訊通訊科技課程資訊',homeHero:['課程入學資訊','人工智能及資訊通訊科技','集中介紹人工智能及資訊通訊科技高級文憑，以及人工智能（榮譽）理學士的課程內容、升學銜接、資助、獎學金及業界合作資訊。',['立即申請','課程列表','獎學金']],announcement:['最新消息','課程資訊摘要','HDAI-ICT / BScAI 課程資訊','入學資訊、課程內容、升學銜接、就業方向、資助、獎學金、業界合作及實習支援已整理成不同正式分頁。'],admissionsPanel:['立即申請','課程入學資訊',[['課程列表','查看高級文憑及學士課程'],['入學資訊','了解入學路線及申請方向'],['升學銜接','了解高級文憑至學士及深造路線'],['財務支援','資助、獎學金及貸款資訊']]],subject:['學科範疇','科技人文','集中展示人工智能及資訊通訊科技相關課程。'],programmeCards:[['高級文憑','人工智能及資訊通訊科技高級文憑','建立程式設計、人工智能、資訊通訊科技、數據、網頁、雲端及網絡基礎。','查看課程詳情 →'],['學士學位','人工智能（榮譽）理學士','深入學習機器學習、深度學習、電腦視覺、自然語言處理及人工智能應用。','查看課程詳情 →']],quick:[['獎學金','資助與獎學金'],['就業支援','畢業出路'],['業界合作','公司合作'],['課程結構','課程內容']]},
    'programmes.html':{title:'課程列表｜SFUHK AI & ICT',hero:['首頁 / 課程列表','課程選擇','人工智能及資訊通訊科技課程列表','按學士學位及副學位分類展示人工智能相關課程，方便學生比較入學、升學及就業方向。'],side:['本頁內容','課程列表','高級文憑','人工智能學士','升學銜接'],directory:[['學士學位課程','人工智能（榮譽）理學士','四年全日制 · 資歷架構第五級 · SSSDP'],['副學位課程','人工智能及資訊通訊科技高級文憑','兩年全日制 / 三年兼讀制 · 資歷架構第四級']],cards:[{h2:'如何選擇？',p:['HDAI-ICT 適合想先建立資訊科技、程式設計、人工智能、網頁、雲端及數據基礎，再升讀學士或投身初階科技工作的學生。BScAI 適合想直接修讀人工智能學士，深入學習機器學習、深度學習、電腦視覺、自然語言處理及人工智能應用的學生。']}]},
    'admissions.html':{title:'入學資訊｜SFUHK AI & ICT',hero:['首頁 / 入學資訊','立即申請','課程入學資訊','本頁整理入學路線，包括直接入讀人工智能學士、先修讀高級文憑，以及日後銜接學士課程。'],side:['入學資訊','概覽','課程列表','學費及支援','升學銜接'],cards:[{h2:'入學路線',info:[['直接入學','中學文憑試或同等學歷 → 人工智能（榮譽）理學士'],['副學位入學','中學文憑試或同等學歷 → 人工智能及資訊通訊科技高級文憑'],['升學銜接','HDAI-ICT → BScAI / BScDET，視乎 GPA 及學術要求']]},{h2:'人工智能學士入學重點',p:['BScAI 是四年全日制人工智能學士課程，JUPAS 編號為 JSSA04，並設 SSSDP 資助學額，適合希望直接修讀人工智能、機器學習、數據、電腦視覺、自然語言處理及應用人工智能的學生。']},{h2:'高級文憑入學重點',p:['HDAI-ICT 是兩年全日制或三年兼讀制高級文憑課程，教學語言以英文為主並輔以中文，適合希望先建立人工智能及資訊通訊科技基礎，再升學或就業的學生。']}],cta:['下一步','學生可先比較課程列表，再查閱獎學金及升學銜接資訊，了解自己適合直接入讀學士課程，還是先修讀高級文憑。','查看課程列表']},
    'hd-aiict.html':{title:'人工智能及資訊通訊科技高級文憑｜SFUHK',hero:['首頁 / 課程列表 / 高級文憑','副學位課程','人工智能及資訊通訊科技高級文憑','HDAI-ICT 是人工智能及資訊通訊科技高級文憑路線，適合希望先建立資訊科技、程式設計、人工智能、數據、網頁、雲端及網絡基礎的學生。'],side:['課程選單','課程簡介','課程結構','升學銜接','畢業出路','財務支援'],cards:[{h2:'課程概覽',info:[['課程編號','HDAI-ICT'],['修讀年期','兩年全日制 / 三年兼讀制'],['授課語言','英文為主，輔以中文'],['資歷架構級別','第四級']]},{h2:'學習內容',h3:['第一年：基礎建立','第二年：應用實踐'],p:['資訊科技、人工智能與元宇宙導論、程式設計、離散數學及線性代數、統計與數據分析、語文及通識科目。','數據結構與演算法、微積分、網絡、雲端與資訊安全、網頁設計與開發、人工智能、機器學習及應用資訊通訊科技專題。']},{h2:'適合的學生',li:['希望進入人工智能或資訊科技行業，但想先以高級文憑打好基礎。','未必直接入讀學士課程，但希望日後銜接 BScAI 或 BScDET。','希望學習程式設計、網頁、雲端、數據及人工智能專題等實用技能。']}],cta:['升學方向','完成 HDAI-ICT 後，學生可按 GPA 及課程要求準備銜接 BScAI 或 BScDET。','查看升學銜接路線']},
    'bscai.html':{title:'人工智能（榮譽）理學士｜SFUHK',hero:['首頁 / 課程列表 / 人工智能學士','學士學位課程','人工智能（榮譽）理學士','BScAI 是人工智能學士路線，主要涵蓋人工智能、機器學習、深度學習、電腦視覺、自然語言處理、數據及跨學科人工智能應用。'],side:['課程選單','課程簡介','課程結構','SSSDP / 獎學金','畢業出路','業界支援'],cards:[{h2:'課程概覽',info:[['課程編號','BSAI / JUPAS JSSA04'],['修讀年期','四年全日制課程'],['授課語言','英文'],['資歷架構級別','第五級'],['資助','符合資格本地學生可獲 SSSDP 資助學額']]},{h2:'學習內容',h3:['第一至二年：人工智能及資訊科技基礎','第三至四年：人工智能專業核心'],p:['程式設計、進階程式設計、離散數學、統計、網頁設計、網絡、雲端、資訊安全、數據結構、人工智能、機器學習及微積分。','軟件工程、深度學習、電腦視覺及影像處理、自然語言處理、資訊科技專業實務與倫理、畢業專題。']},{h2:'應用人工智能選修方向',li:['大數據及商業智能','醫療健康科學中的大數據及人工智能','機械人中的人工智能','教育中的人工智能','翻譯中的人工智能','虛擬實境、元宇宙及遊戲科技相關選修']}],cta:['畢業後的深造方向','完成 BScAI 後，可申請人工智能、數據科學、電腦科學、網絡安全或軟件工程等碩士、哲學碩士或博士課程。','查看深造路線']},
    'articulation.html':{title:'升學銜接路線｜SFUHK AI & ICT',hero:['首頁 / 升學銜接','深造及升學','升學銜接路線','由高級文憑銜接至人工智能學士或其他相關學士課程，再到碩士、哲學碩士或博士深造路線。'],side:['升學路線','由高級文憑開始','學士學位','深造課程','畢業出路'],pathway:[['HDAI-ICT','完成兩年高級文憑，建立人工智能、資訊通訊科技、程式設計、網頁、雲端、數據及專題基礎。'],['BScAI / BScDET','達到指定 GPA 及學術要求後，可準備銜接相關學士課程。'],['碩士 / 哲學碩士 / 博士','完成 BScAI 後，可申請人工智能、數據科學、電腦科學、網絡安全及軟件工程等深造課程。']],cards:[{h2:'高級文憑 → 學士',p:['HDAI-ICT 畢業生如達到最低 GPA 要求，可準備銜接 SFUHK 相關學士課程，例如 BScAI 或 BScDET。實際入學及學分豁免安排以大學最新規定為準。']},{h2:'學士 → 深造',p:['BScAI 畢業後可繼續申請授課式碩士、深造文憑、哲學碩士或博士課程。若希望走研究路線，畢業專題、GPA、推薦信及人工智能或數據專題經驗會尤其重要。']}]},
    'scholarships.html':{title:'資助與獎學金｜SFUHK AI & ICT',hero:['首頁 / 學生支援 / 獎學金','資助與獎學金','資助與獎學金','本頁整理 BScAI 及 HDAI-ICT 學生可留意的資助、獎學金及貸款資訊。'],side:['學生支援','獎學金','財務支援','入學資訊','就業支援'],cards:[{h2:'獎學金',info:[['JUPAS 課程獎學金','BScAI 可按 JUPAS 或課程獎學金安排考慮。'],['入學獎學金計劃','按入學成績考慮，例如入學獎學金或學業成就獎學金。'],['校內銜接獎學金','適用於合資格校內銜接學生。'],['其他獎學金','學生可留意校內及外部獎學金計劃。']]},{h2:'財務支援',li:['SSSDP：BScAI / JSSA04 本地合資格學生可獲政府資助。','FASP：全日制專上學生可按家庭入息申請資助。','NLSPS / ENLS：免入息審查貸款或擴展貸款。','助學金：學生可按校內最新公布申請。']},{h2:'重要提醒',p:['多項獎學金會由大學按成績或資格考慮，不同獎學金通常不可同時領取。實際資格、金額及申請安排以 SFUHK 最新公布為準。']}]},
    'career.html':{title:'畢業出路｜SFUHK AI & ICT',hero:['首頁 / 就業支援','就業支援','畢業出路','AI & ICT 課程裝備學生掌握人工智能、軟件開發、數據應用、雲端技術及資訊系統等專業能力，支援學生規劃升學及就業方向。'],side:['畢業出路','職涯方向','業界合作','深造升學','學生支援'],grid:[['程式設計 / 軟件開發','程式員、軟件開發員、網頁開發員、應用程式開發員、前端及後端工程師。'],['人工智能 / 數據','人工智能數據分析師、機器學習工程師、深度學習工程師、大數據工程師。'],['系統 / 雲端','系統分析師、數據庫開發員、雲端、網絡及資訊安全相關技術職位。'],['應用人工智能','金融科技人工智能開發、醫療人工智能開發、教育、翻譯及機械人相關人工智能應用。']],cards:[{h2:'職涯準備',p:['學生可透過職涯規劃、履歷及面試準備、職涯講座、公司參觀、實習資訊及畢業就業支援，逐步建立投身人工智能、資訊通訊科技、軟件開發、數據及雲端科技行業所需的專業準備。']}]},
    'industry.html':{title:'業界合作｜SFUHK AI & ICT',hero:['首頁 / 業界合作','業界合作','業界合作及實習支援','本頁展示實習、公司合作、職涯講座、公司參觀及業界支援，協助學生了解人工智能及資訊通訊科技行業發展。'],side:['業界合作','概覽','就業支援','高級文憑','人工智能學士'],cards:[{h2:'業界支援',p:['課程設有業界連繫及實習支援，包括實習機會、客席講座、公司參觀、職涯規劃、業界分享及就業資訊，協助學生了解人工智能及資訊通訊科技行業的最新發展。']}]},
    'faq.html':{title:'常見問題｜SFUHK AI & ICT',hero:['首頁 / 搜尋 / 常見問題','搜尋 / 常見問題','常見問題','本頁整理高級文憑、人工智能學士、升學銜接、資助、獎學金及業界合作的常見問題。'],faq:[['HDAI-ICT 是否一定要很擅長程式設計？','不一定。課程會由資訊科技、程式設計、數學、統計及人工智能基礎開始。不過，如果學生有興趣自行練習 Python 或網頁開發，會更容易跟上課程。'],['完成高級文憑是否一定能升讀學士課程？','不是自動保證。一般需要完成課程並達到指定 GPA 或學術要求，實際安排以大學最新公布為準。'],['完成 BScAI 後可以繼續深造嗎？','可以。學生可申請人工智能、機器學習、數據科學、電腦科學、網絡安全及軟件工程等方向的碩士、哲學碩士或博士課程。'],['是否有公司合作？','課程設有業界合作及實習支援，讓學生接觸科技公司、行業講座、公司參觀及相關就業資訊。'],['資助和獎學金有甚麼分別？','資助通常指政府、助學金或貸款支援；獎學金通常按成績、入學表現、銜接路線或特定資格考慮。']]}
  }
};

const EN={common:{university:'Saint Francis University',site:'AI & ICT Programme Information',util:['Announcement','Apply Now','Student Support','Search'],nav:['Admissions','Programme List','HDAI-ICT','BScAI','Articulation','Scholarships','Career','Industry'],lang:['繁體中文','English','简体中文'],footer:'Information is subject to the latest official announcements from SFUHK and JUPAS.',mobile:['Announcement','Apply Now','Student Support','Search / FAQ']},pages:{
'index.html':{title:'SFUHK AI & ICT Programme Information',homeHero:['Programme Admissions','Artificial Intelligence & ICT','This site presents the Higher Diploma in Artificial Intelligence and ICT and the Bachelor of Science (Honours) in Artificial Intelligence, including programme structure, articulation, financial support, scholarships and industry connections.',['Apply Now','Programme List','Scholarships']],announcement:['Announcement','Latest Programme Information','HDAI-ICT / BScAI Programme Information','Admissions, programme structure, articulation, career pathways, funding, scholarships, industry collaboration and internship support are organised into dedicated pages.'],admissionsPanel:['Apply Now','Programme Admissions',[['Programme List','View higher diploma and bachelor programmes'],['Admissions','Understand admissions routes and application directions'],['Articulation','Explore HD to degree and postgraduate pathways'],['Financial Support','Funding, scholarships and loan information']]],subject:['Subject Areas','Techno-Humanities','AI and ICT related programmes are presented in one place.'],programmeCards:[['Higher Diploma','Higher Diploma in Artificial Intelligence and Information and Communication Technology','Build foundations in programming, artificial intelligence, ICT, data, web, cloud and networking.','View Programme Details →'],['Bachelor Degree','Bachelor of Science (Honours) in Artificial Intelligence','Study machine learning, deep learning, computer vision, natural language processing and applied AI in greater depth.','View Programme Details →']],quick:[['Scholarships','Financial support and scholarships'],['Career Services','Career pathways'],['Industry Partners','Industry collaboration'],['Programme Structure','Programme content']]},
'programmes.html':{title:'Programme List｜SFUHK AI & ICT',hero:['Home / Programme List','Programme Offerings','AI & ICT Programme List','AI-related programmes are organised by bachelor degree and sub-degree level, helping students compare admissions, articulation and career pathways.'],side:['In this section','Programme List','HDAI-ICT','BScAI','Articulation'],directory:[['Undergraduate Programmes','Bachelor of Science (Honours) in Artificial Intelligence','4-year full-time · QF Level 5 · SSSDP'],['Sub-degree Programmes','Higher Diploma in Artificial Intelligence and Information and Communication Technology','2-year full-time / 3-year part-time · QF Level 4']],cards:[{h2:'How to choose?',p:['HDAI-ICT is suitable for students who want to build foundations in IT, programming, AI, web, cloud and data before progressing to degree study or entry-level technology work. BScAI is suitable for students who want to study an AI bachelor degree directly and go deeper into machine learning, deep learning, computer vision, natural language processing and applied AI.']}]},
'admissions.html':{title:'Admissions｜SFUHK AI & ICT',hero:['Home / Admissions','Apply Now','Programme Admissions','This page outlines admissions pathways, including direct entry to the AI bachelor degree, entry to the higher diploma, and later articulation to bachelor degree study.'],side:['Admissions','Overview','Programme List','Fees & Support','Articulation'],cards:[{h2:'Admissions Pathways',info:[['Direct Entry','HKDSE or equivalent qualifications → Bachelor of Science (Honours) in Artificial Intelligence'],['Sub-degree Entry','HKDSE or equivalent qualifications → Higher Diploma in Artificial Intelligence and ICT'],['Articulation','HDAI-ICT → BScAI / BScDET, subject to GPA and academic requirements']]},{h2:'BScAI Admissions Highlights',p:['BScAI is a four-year full-time bachelor degree in artificial intelligence. Its JUPAS code is JSSA04 and SSSDP subsidised places are available. It is suitable for students who want to study AI, machine learning, data, computer vision, natural language processing and applied AI directly.']},{h2:'HDAI-ICT Admissions Highlights',p:['HDAI-ICT is a two-year full-time or three-year part-time higher diploma. The medium of instruction is mainly English supplemented by Chinese. It is suitable for students who want to build AI and ICT foundations before further study or employment.']}],cta:['Next Step','Students may compare the programme list first, then review scholarships and articulation information to decide whether direct degree entry or the higher diploma route is more suitable.','View Programme List']},
'hd-aiict.html':{title:'Higher Diploma in AI & ICT｜SFUHK',hero:['Home / Programme List / HDAI-ICT','Sub-degree Programme','Higher Diploma in Artificial Intelligence and ICT','HDAI-ICT is a higher diploma pathway in artificial intelligence and ICT, suitable for students who want to build foundations in IT, programming, AI, data, web, cloud and networking.'],side:['Programme Menu','Introduction','Programme Structure','Articulation','Career Pathways','Financial Support'],cards:[{h2:'Programme Overview',info:[['Programme Code','HDAI-ICT'],['Duration','2-year full-time / 3-year part-time'],['Medium','English supplemented by Chinese'],['QF Level','Level 4']]},{h2:'What do students study?',h3:['Year 1: Foundation','Year 2: Application'],p:['Introduction to IT, AI and Metaverse, Computer Programming, Discrete Mathematics and Linear Algebra, Statistics and Data Analysis, language and general education subjects.','Data Structures and Algorithms, Calculus, Network, Cloud and Security, Web Design and Development, Artificial Intelligence, Machine Learning and Applied ICT Project.']},{h2:'Suitable Students',li:['Students who want to enter AI or IT but prefer to build foundations through a higher diploma first.','Students who may not enter degree study directly but want to articulate to BScAI or BScDET later.','Students who want practical skills in programming, web, cloud, data and AI projects.']}],cta:['Articulation Direction','After completing HDAI-ICT, students may prepare to articulate to BScAI or BScDET subject to GPA and programme requirements.','View Articulation Pathway']},
'bscai.html':{title:'Bachelor of Science (Honours) in Artificial Intelligence｜SFUHK',hero:['Home / Programme List / BScAI',"Bachelor's Degree Programme",'Bachelor of Science (Honours) in Artificial Intelligence','BScAI is an artificial intelligence bachelor degree pathway covering AI, machine learning, deep learning, computer vision, natural language processing, data and cross-disciplinary AI applications.'],side:['Programme Menu','Introduction','Programme Structure','SSSDP / Scholarships','Career Pathways','Industry Support'],cards:[{h2:'Programme Overview',info:[['Programme Code','BSAI / JUPAS JSSA04'],['Duration','4-year full-time programme'],['Medium','English'],['QF Level','Level 5'],['Funding','SSSDP subsidised places are available for eligible local students']]},{h2:'What do students study?',h3:['Year 1–2: AI and IT Foundations','Year 3–4: Advanced AI Core'],p:['Computer programming, advanced programming, discrete mathematics, statistics, web design, network, cloud, security, data structures, artificial intelligence, machine learning and calculus.','Software engineering, deep learning, computer vision and image processing, natural language processing, IT professional practice and ethics, and the final year project.']},{h2:'Applied AI Elective Areas',li:['Big data and business intelligence','Big data and AI in health sciences','Artificial intelligence in robotics','Artificial intelligence in education','Artificial intelligence in translation','VR, metaverse and game technology related electives']}],cta:['Further Study after Graduation','After completing BScAI, graduates may apply for master, MPhil or PhD programmes in AI, data science, computer science, cybersecurity or software engineering.','View Postgraduate Pathway']},
'articulation.html':{title:'Articulation Pathway｜SFUHK AI & ICT',hero:['Home / Articulation','Further Study','Articulation Pathway','This page outlines the pathway from the higher diploma to BScAI or other related bachelor programmes, and then to master, MPhil or PhD study.'],side:['Pathway','Start with HD','Bachelor Degree','Further Study','Career'],pathway:[['HDAI-ICT','Complete the two-year higher diploma and build foundations in AI, ICT, programming, web, cloud, data and projects.'],['BScAI / BScDET','Students who meet the specified GPA and academic requirements may prepare to articulate to related bachelor degree programmes.'],['Master / MPhil / PhD','After completing BScAI, graduates may apply for postgraduate programmes in AI, data science, computer science, cybersecurity and software engineering.']],cards:[{h2:'HD → Degree',p:['HDAI-ICT graduates who meet the minimum GPA requirement may prepare to articulate to related SFUHK bachelor programmes such as BScAI or BScDET. Actual admission and credit transfer arrangements are subject to the latest university regulations.']},{h2:'Degree → Postgraduate',p:['After BScAI, graduates may apply for taught master degrees, postgraduate diplomas, MPhil or PhD programmes. For research pathways, the final year project, GPA, recommendation letters and AI or data project experience are especially important.']}]},
'scholarships.html':{title:'Scholarships & Financial Assistance｜SFUHK AI & ICT',hero:['Home / Student Support / Scholarships','Scholarships & Financial Assistance','Scholarships & Financial Assistance','This page presents funding, scholarships and loan information relevant to BScAI and HDAI-ICT students.'],side:['Student Support','Scholarships','Financial Assistance','Admissions','Career Services'],cards:[{h2:'Scholarships',info:[['JUPAS Programme Scholarships','BScAI may be considered under JUPAS or programme scholarship arrangements.'],['Admission Scholarship Schemes','Considered based on admission results, such as entrance scholarships or academic achievement scholarships.'],['Internal Articulation Scholarships','Applicable to eligible internal articulation students.'],['Other Scholarships','Students may refer to internal and external scholarship schemes.']]},{h2:'Financial Assistance',li:['SSSDP: eligible local BScAI / JSSA04 students may receive government subsidy.','FASP: full-time post-secondary students may apply for assistance based on family income.','NLSPS / ENLS: non-means-tested loan schemes or extended loan schemes.','Bursaries: students may apply according to the latest internal announcements.']},{h2:'Important Note',p:['Many scholarships are considered by the university based on results or eligibility. Different scholarships are usually not tenable concurrently. Actual eligibility, amount and application arrangements are subject to the latest SFUHK announcements.']}]},
'career.html':{title:'Career Pathways｜SFUHK AI & ICT',hero:['Home / Career Services','Career Services','Career Pathways','AI & ICT programmes equip students with professional capabilities in artificial intelligence, software development, data applications, cloud technology and information systems, supporting both further study and career planning.'],side:['Career','Career Pathways','Industry Partners','Further Study','Student Support'],grid:[['Programming / Software','Programmer, software developer, web developer, app developer, front-end and back-end engineer.'],['AI / Data','AI data analyst, machine learning engineer, deep learning engineer and big data engineer.'],['Systems / Cloud','System analyst, database developer, and technical roles related to cloud, networking and cybersecurity.'],['Applied AI','AI and FinTech developer, AI and healthcare developer, and AI applications in education, translation and robotics.']],cards:[{h2:'Career Readiness',p:['Students can build career readiness through career planning, CV and interview preparation, career talks, company visits, internship information and graduate employment support, preparing for careers in AI, ICT, software development, data and cloud technology.']}]},
'industry.html':{title:'Industry Collaboration｜SFUHK AI & ICT',hero:['Home / Industry Collaboration','Industry Collaboration','Industry Collaboration and Internship Support','This page presents internships, industry collaboration, career talks, company visits and industry support, helping students understand developments in the AI and ICT sectors.'],side:['Industry','Overview','Career Services','HDAI-ICT','BScAI'],cards:[{h2:'Industry Support',p:['The programmes provide industry connections and internship support, including internship opportunities, guest lectures, company visits, career planning, industry sharing and employment information, helping students understand the latest developments in AI and ICT.']}]},
'faq.html':{title:'FAQ｜SFUHK AI & ICT',hero:['Home / Search / FAQ','Search / FAQ','Frequently Asked Questions','This page answers common questions about the higher diploma, AI bachelor degree, articulation, funding, scholarships and industry collaboration.'],faq:[['Do HDAI-ICT students need strong coding skills?','Not necessarily. The programme starts from foundations in IT, programming, mathematics, statistics and artificial intelligence. Students who practise Python or web development on their own may find it easier to follow the programme.'],['Does completing the higher diploma guarantee entry to a degree programme?','No. Students usually need to complete the programme and meet the specified GPA or academic requirements. Actual arrangements are subject to the latest university announcements.'],['Can BScAI graduates continue to further study?','Yes. Graduates may apply for master, MPhil or PhD programmes in areas such as AI, machine learning, data science, computer science, cybersecurity and software engineering.'],['Are there industry collaborations?','The programmes provide industry collaboration and internship support, allowing students to engage with technology companies, industry talks, company visits and employment-related information.'],['What is the difference between funding and scholarships?','Funding usually refers to government support, bursaries or loans. Scholarships are usually considered based on results, admission performance, articulation route or specific eligibility.']]}}};

function toSimpText(text){const map={'學':'学','體':'体','資':'资','訊':'讯','課':'课','與':'与','榮':'荣','譽':'誉','獎':'奖','業':'业','聯':'联','連':'连','繫':'系','參':'参','觀':'观','職':'职','劃':'划','準':'准','確':'确','畢':'毕','頁':'页','網':'网','簡':'简','選':'选','擇':'择','級':'级','憑':'凭','語':'语','為':'为','會':'会','實':'实','習':'习','應':'应','該':'该','現':'现','內':'内','單':'单','後':'后','將':'将','開':'开','關':'关','導':'导','覽':'览','這':'这','個':'个','較':'较','別':'别','條':'条','徑':'径','啲':'些','咩':'什么','唔':'不','嘅':'的','喺':'在','睇':'看','寫':'写','過':'过','話':'说','對':'对','讓':'让','風':'风','並':'并','設':'设','時':'时','間':'间','維':'维','護':'护','務':'务','碼':'码','據':'据','數':'数','優':'优','點':'点','適':'适','門':'门','報':'报','讀':'读','銜':'衔','請':'请','當':'当','長':'长','總':'总','結':'结','標':'标','題':'题','動':'动','廣':'广','東':'东','項':'项','嗎':'吗','區':'区','顯':'显','軟':'软','雲':'云','專':'专','規':'规','說':'说','師':'师','員':'员','術':'术','絡':'络','圖':'图','處':'处','進':'进','階':'阶','離':'离','線':'线','擬':'拟','醫':'医','療':'疗','經':'经','驗':'验','構':'构','測':'测','試':'试'};return text.replace(/[\s\S]/g,ch=>map[ch]||ch).replace(/資訊通訊/g,'信息通信').replace(/資歷架構/g,'资历架构');}
function deepSimp(v){if(typeof v==='string')return toSimpText(v);if(Array.isArray(v))return v.map(deepSimp);if(v&&typeof v==='object')return Object.fromEntries(Object.entries(v).map(([k,val])=>[k,deepSimp(val)]));return v;}
function getData(lang){return lang==='en'?EN:(lang==='zh-hans'?deepSimp(ZH):ZH);}
function setText(sel,text,root=document){const el=root.querySelector(sel);if(el&&text!==undefined)el.textContent=text;}
function setAll(sel,texts,root=document){root.querySelectorAll(sel).forEach((el,i)=>{if(texts&&texts[i]!==undefined)el.textContent=texts[i];});}
function setInfo(card,info){if(!info)return;card.querySelectorAll('.info-table>div').forEach((row,i)=>{if(!info[i])return;setText('strong',info[i][0],row);setText('span',info[i][1],row);});}
function setHero(hero){if(!hero)return;setText('.page-hero .breadcrumb',hero[0]);setText('.page-hero .eyebrow',hero[1]);setText('.page-hero h1',hero[2]);setText('.page-hero p:last-child',hero[3]);}
function setSide(side){if(!side)return;setText('.side-nav strong',side[0]);setAll('.side-nav a',side.slice(1));}
function setCards(cards){if(!cards)return;document.querySelectorAll('.content-main>.content-card').forEach((card,i)=>{const d=cards[i];if(!d)return;setText('h2',d.h2,card);setInfo(card,d.info);setAll('h3',d.h3,card);setAll('p',d.p,card);setAll('li',d.li,card);});}
function setCta(cta){if(!cta)return;setText('.cta-banner h2',cta[0]);setText('.cta-banner p',cta[1]);setText('.cta-banner a',cta[2]);}
function setGrid(grid){if(!grid)return;document.querySelectorAll('.subpage-grid article').forEach((a,i)=>{if(!grid[i])return;setText('h3',grid[i][0],a);setText('p',grid[i][1],a);});}
function setPathway(pathway){if(!pathway)return;document.querySelectorAll('.pathway-line article').forEach((a,i)=>{if(!pathway[i])return;setText('h3',pathway[i][0],a);setText('p',pathway[i][1],a);});}
function setDirectory(dir){if(!dir)return;document.querySelectorAll('.directory-block').forEach((b,i)=>{if(!dir[i])return;setText('h2',dir[i][0],b);setText('.directory-item strong',dir[i][1],b);setText('.directory-item em',dir[i][2],b);});}
function setFaq(faq){if(!faq)return;document.querySelectorAll('.faq details').forEach((d,i)=>{if(!faq[i])return;setText('summary',faq[i][0],d);setText('p',faq[i][1],d);});}
function setHome(p){if(!p||!p.homeHero)return;setText('.hero-copy .eyebrow',p.homeHero[0]);setText('.hero-copy h1',p.homeHero[1]);setText('.hero-copy .lead',p.homeHero[2]);setAll('.hero-actions .button',p.homeHero[3]);setText('.announcement .eyebrow',p.announcement[0]);setText('.announcement h2',p.announcement[1]);setText('.announcement-card h3',p.announcement[2]);setText('.announcement-card p',p.announcement[3]);setText('.admissions-panel .eyebrow',p.admissionsPanel[0]);setText('.admissions-panel h2',p.admissionsPanel[1]);document.querySelectorAll('.admission-links a').forEach((a,i)=>{const item=p.admissionsPanel[2][i];if(!item)return;setText('strong',item[0],a);setText('span',item[1],a);});setText('.section .section-heading .eyebrow',p.subject[0]);setText('.section .section-heading h2',p.subject[1]);setText('.section .section-heading p:last-child',p.subject[2]);document.querySelectorAll('.programme-card').forEach((card,i)=>{const item=p.programmeCards[i];if(!item)return;setText('.tag',item[0],card);setText('h3',item[1],card);setText('p',item[2],card);setText('.text-link',item[3],card);});document.querySelectorAll('.quick-links a').forEach((a,i)=>{const item=p.quick[i];if(!item)return;setText('strong',item[0],a);setText('span',item[1],a);});}
function removeInternalNotes(){document.querySelectorAll('.content-card').forEach(card=>{const s=card.textContent||'';if(s.includes('建議網站用字'))card.remove();if(s.includes('網站文字可以寫')||s.includes('保證工作 offer'))card.innerHTML='<h2></h2><p></p>';});}
function addLanguageSwitchers(c){const markup=`<div class="language-switcher" aria-label="Language selector"><button type="button" data-lang="zh-hant">${c.lang[0]}</button><button type="button" data-lang="en">${c.lang[1]}</button><button type="button" data-lang="zh-hans">${c.lang[2]}</button></div>`;const utility=document.querySelector('.utility-bar nav');if(utility&&!utility.querySelector('.language-switcher'))utility.insertAdjacentHTML('beforeend',markup);const header=document.querySelector('.main-header');const menu=header?.querySelector('.menu-toggle');if(menu&&!header.querySelector('.mobile-language-switcher'))menu.insertAdjacentHTML('beforebegin',markup.replace('language-switcher','language-switcher mobile-language-switcher'));}
function addMobileLinks(c){if(!nav||nav.querySelector('.mobile-utility-links'))return;nav.insertAdjacentHTML('afterbegin',`<div class="mobile-utility-links"><a href="index.html#announcement">${c.mobile[0]}</a><a href="admissions.html">${c.mobile[1]}</a><a href="scholarships.html">${c.mobile[2]}</a><a href="faq.html">${c.mobile[3]}</a></div>`);}
function activeLang(){return localStorage.getItem('sfu-site-lang')||'zh-hant';}
function updateActiveNav(){document.querySelectorAll('.nav a').forEach(link=>{const href=link.getAttribute('href')||'';const page=href.split('#')[0]||'index.html';link.classList.toggle('active',page===currentPage);});}
function applyLanguage(lang){const data=getData(lang),c=data.common,page=data.pages[currentPage]||data.pages['index.html'];document.documentElement.lang=lang==='en'?'en':(lang==='zh-hans'?'zh-Hans':'zh-Hant-HK');if(page.title)document.title=page.title;setText('.utility-bar>span',c.university);setText('.brand strong',c.university);setText('.brand small',c.site);setAll('.utility-bar nav>a',c.util);setAll('.nav>a',c.nav);setText('.footer strong',c.university);setText('.footer span',c.site);setText('.footer p',c.footer);document.querySelectorAll('.language-switcher button').forEach((b,i)=>{b.textContent=c.lang[i];b.classList.toggle('active',b.dataset.lang===lang);});setAll('.mobile-utility-links a',c.mobile);setHome(page);setHero(page.hero);setSide(page.side);setCards(page.cards);setCta(page.cta);setGrid(page.grid);setPathway(page.pathway);setDirectory(page.directory);setFaq(page.faq);localStorage.setItem('sfu-site-lang',lang);updateActiveNav();}
function initReveal(){const targets=document.querySelectorAll('.programme-card,.structure-grid article,.career-grid article,.subpage-grid article,.content-card,.directory-block,.cta-banner,.partner-strip span,.quick-links a,.faq details,.pathway-line article');if('IntersectionObserver'in window){const obs=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(!entry.isIntersecting)return;entry.target.classList.add('reveal-in');obs.unobserve(entry.target);});},{threshold:.14,rootMargin:'0px 0px -8% 0px'});targets.forEach(el=>{el.classList.add('reveal-ready');obs.observe(el);});}else targets.forEach(el=>el.classList.add('reveal-in'));}
async function softNavigate(url,replace=false){if(softNavigating)return;softNavigating=true;const oldMain=document.querySelector('main');try{oldMain?.classList.add('main-leave');const res=await fetch(url.href,{cache:'no-cache'});if(!res.ok)throw new Error('Navigation fetch failed');const html=await res.text();const doc=new DOMParser().parseFromString(html,'text/html');const newMain=doc.querySelector('main');if(!newMain)throw new Error('No main content found');await new Promise(r=>setTimeout(r,120));document.querySelector('main')?.replaceWith(newMain);currentPage=url.pathname.split('/').pop()||'index.html';if(replace)history.replaceState({soft:true},'',url.href);else history.pushState({soft:true},'',url.href);removeInternalNotes();applyLanguage(activeLang());initReveal();document.querySelector('main')?.classList.add('main-enter');nav?.classList.remove('open');toggle?.setAttribute('aria-expanded','false');if(url.hash){setTimeout(()=>document.querySelector(url.hash)?.scrollIntoView({behavior:'smooth'}),60);}else{window.scrollTo({top:0,behavior:'smooth'});}setTimeout(()=>document.querySelector('main')?.classList.remove('main-enter'),300);}catch(e){window.location.href=url.href;}finally{softNavigating=false;}}

removeInternalNotes();addLanguageSwitchers(ZH.common);addMobileLinks(ZH.common);applyLanguage(activeLang());initReveal();updateActiveNav();
document.addEventListener('click',e=>{const btn=e.target.closest('.language-switcher button');if(btn){applyLanguage(btn.dataset.lang);return;}const a=e.target.closest('a[href]');if(!a)return;const href=a.getAttribute('href');if(!href||href.startsWith('mailto:')||href.startsWith('tel:')||a.target==='_blank')return;const url=new URL(href,location.href);if(url.origin!==location.origin)return;if(url.pathname===location.pathname&&url.hash){e.preventDefault();document.querySelector(url.hash)?.scrollIntoView({behavior:'smooth'});history.pushState({soft:true},'',url.href);return;}if(url.pathname.endsWith('.html')||url.pathname===location.pathname||url.pathname.endsWith('/SFU/')||url.pathname.endsWith('/SFU')){e.preventDefault();softNavigate(url);}},true);
window.addEventListener('popstate',()=>softNavigate(new URL(location.href),true));
toggle?.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open));});
window.addEventListener('scroll',()=>topButton?.classList.toggle('show',window.scrollY>600));
topButton?.addEventListener('click',()=>window.scrollTo({top:0,behavior:'smooth'}));
